# Generated by Django 5.0.4 on 2024-04-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyN5Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('kanji', models.IntegerField(default=0)),
            ],
        ),
    ]
